'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Leaf,MapPin,Clock,Sprout,ArrowUpRight,Info,Flame} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import initial from '../public/data.json';
import 'leaflet/dist/leaflet.css';
type Plant=typeof initial.plants[number];
type LType=typeof import('leaflet');
const regions=['All Kalimantan','West Kalimantan','Central Kalimantan','South Kalimantan','East Kalimantan','North Kalimantan'];
function Sources({items}:{items:{label:string;url:string}[]}){return <div className="links">{items.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label}<ArrowUpRight size={14}/></a>)}</div>}
function HabitatMap({plants,selected,onSelect}:{plants:Plant[];selected:string;onSelect:(id:string)=>void}){
 const el=useRef<HTMLDivElement>(null),map=useRef<import('leaflet').Map|null>(null),layer=useRef<import('leaflet').LayerGroup|null>(null);
 const [leaflet,setLeaflet]=useState<LType|null>(null),[error,setError]=useState(false);
 useEffect(()=>{let cancelled=false;import('leaflet').then(L=>{if(cancelled||!el.current)return;map.current=L.map(el.current,{scrollWheelZoom:false}).setView([.1,114.4],6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:13,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>setError(true)).addTo(map.current);layer.current=L.layerGroup().addTo(map.current);setLeaflet(L);}).catch(()=>setError(true));return()=>{cancelled=true;map.current?.remove();map.current=null;layer.current=null;};},[]);
 useEffect(()=>{if(!leaflet||!layer.current)return;layer.current.clearLayers();plants.forEach(p=>{const tip=document.createElement('span');tip.textContent=p.name+' · approximate regional reference';leaflet.circleMarker([p.lat,p.lon],{radius:p.id===selected?13:8,color:p.id===selected?'#173e34':'#fff',weight:3,fillColor:p.status==='CR'?'#d96743':p.status==='EW'?'#7b64a3':'#168069',fillOpacity:1}).bindTooltip(tip).on('click',()=>onSelect(p.id)).addTo(layer.current!)});},[leaflet,plants,selected,onSelect]);
 return <><div ref={el} className="map" aria-label="Map of approximate regional plant references"/>{error&&<p className="note">Map tiles could not load. Regional coordinates are available in the plant profile.</p>}</>;
}
export default function Home(){
 const [data,setData]=useState(initial),[id,setId]=useState('ramin'),[region,setRegion]=useState('All Kalimantan'),[date,setDate]=useState(initial.lastReview),[fetchError,setFetchError]=useState(false);
 useEffect(()=>{fetch('/data.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(!d||typeof d!=='object'||!('plants' in d)||!('news' in d)||!Array.isArray(d.plants)||!Array.isArray(d.news))throw Error();setData(d as typeof initial)}).catch(()=>setFetchError(true))},[]);
 const plants=useMemo(()=>data.plants.filter(p=>region==='All Kalimantan'||p.region===region),[data.plants,region]);
 const p=plants.find(x=>x.id===id)||plants[0],report=data.reports.find(r=>r.date===date),news=data.news.filter(n=>region==='All Kalimantan'||n.region===region);
 return <main><header><a href="/" className="brand"><span><Leaf/></span>Hutan<b>Watch</b></a><small>KALIMANTAN · FLORA OBSERVATORY</small><em>Reviewed {data.lastReview}</em></header>
 <section className="intro"><div><label>FIRE EXPOSURE & CONSERVATION</label><h1>Kalimantan flora risk dashboard</h1><p>Regional fire evidence, plants to monitor and routes to recovery.</p></div><aside><Clock size={19}/><b>9–23 September 2026<small>{data.monitoring.label} · target 17:00 WIB</small></b></aside></section>
 {fetchError&&<p className="notice">Showing the bundled evidence snapshot; the latest data file could not be loaded.</p>}
 <section className="stats"><div>Selected flora<strong>{data.plants.length}<Leaf/></strong><small>Watchlist, not a full species inventory</small></div><div>Peat habitat concern<strong>{data.plants.filter(p=>p.risk==='Peat habitat concern').length}<Flame/></strong><small>Screening inference; exposure unverified</small></div><div>Species deaths verified<strong>—<Sprout/></strong><small>None established in the sources reviewed</small></div><div>Latest source publication<strong>{data.news.map(n=>n.date).sort().at(-1)?.slice(8)} Sep<Clock/></strong><small>Review date: {data.lastReview}</small></div></section>
 <Tabs defaultValue="map" className="dashboard-tabs"><div className="tabbar"><TabsList variant="line"><TabsTrigger value="map">Risk & map</TabsTrigger><TabsTrigger value="recovery">Recovery pathways</TabsTrigger><TabsTrigger value="daily">Daily evidence log</TabsTrigger></TabsList><a href="https://firms.modaps.eosdis.nasa.gov/map/#d:24hrs;@114.3,0.1,6.0z" target="_blank" rel="noreferrer">NASA fire map <ArrowUpRight size={15}/></a></div>
 <TabsContent value="map"><div className="filterbar"><div><h2>Where to focus</h2><p>Choose a region or plant to inspect its evidence.</p></div><Select value={region} onValueChange={v=>setRegion(v||'All Kalimantan')}><SelectTrigger aria-label="Filter by Kalimantan region"><SelectValue/></SelectTrigger><SelectContent>{regions.map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select></div>
 <section className="workspace"><div><div className="mapbox"><HabitatMap plants={plants} selected={p?.id||''} onSelect={setId}/><div className="key"><span className="cr">● Critically endangered</span><span className="ew">● Extinct in the wild</span><span>● Other watchlist plants</span></div></div><p className="note"><Info size={15}/>Markers indicate approximate regional references. They are not surveyed individuals, fire detections or confirmed species losses.</p>
 <div className="plantlist">{plants.map(x=><button key={x.id} onClick={()=>setId(x.id)} aria-pressed={p?.id===x.id} className={x.id===p?.id?'selected':''}><Leaf size={18}/><span><b>{x.name}</b><i>{x.scientific}</i><small>{x.risk}</small></span><mark className={x.status}>{x.status==='?'?'Unverified':x.status}</mark></button>)}</div>{!plants.length&&<div className="empty">No verified plant reference is stored for this region. See the regional evidence below; this gap does not establish low risk.</div>}
 <section className="regional"><h2>Regional evidence</h2>{data.regions.filter(r=>region==='All Kalimantan'||r.name===region).map(r=><article key={r.name}><div><b>{r.name}</b><span>{r.status}</span></div><p>{r.detail}</p>{r.url?<a href={r.url} target="_blank" rel="noreferrer">Source · {r.date} <ArrowUpRight size={13}/></a>:<small>Reviewed {r.date} · evidence gap</small>}</article>)}</section></div>
 {p&&<article className="detail"><label>PLANT PROFILE</label><div className="plant-visual"><img src={p.image} alt={`${p.name} (${p.scientific})`} loading="lazy"/><div><mark className={p.status}>{p.statusLabel}</mark><h2>{p.name}</h2></div></div><i>{p.scientific}</i><p className="location"><MapPin size={15}/>{p.region}</p><div className="warning"><b>{p.risk}</b><p>{p.riskBasis}</p></div><h3>Confirmed fire impact</h3><p>{p.impact}</p><h3>Location & availability</h3><p>{p.location}</p><div className="population"><b>Population now</b><p>{p.population}</p></div><p className="coordinate">Approximate anchor: {p.lat}°, {p.lon}°</p><p>{p.availability}</p><h3>Plant parts & recovery material</h3><p>{p.parts}</p><h3><Sprout size={17}/>Recovery potential</h3><p>{p.recovery}</p><Sources items={[...p.sources,...p.riskSources]}/></article>}</section>
 <section className="news"><h2>Latest retained reports</h2><p className="note">Publication dates below are separate from the date this dashboard was reviewed.</p><div className="newsgrid">{news.map(n=><article key={n.id}><small>{n.date} · {n.publisher}</small><h3>{n.title}</h3><mark>{n.evidence}</mark><p>{n.summary}</p><a href={n.url} target="_blank" rel="noreferrer">Read source <ArrowUpRight size={14}/></a></article>)}</div>{!news.length&&<p>No current report retained for this region.</p>}</section></TabsContent>
 <TabsContent value="recovery"><section className="content"><label>FROM SURVIVAL TO RESTORATION</label><h2>Recovery starts with living material.</h2><p>A dead plant cannot be revived. Surviving trees, viable seeds, seedlings and suitable habitat can help a population recover.</p><div className="cards">{[{title:'Protect survivors',text:'After the site is safe, restoration teams can assess living crowns, stems and roots, identify species and protect remaining seed trees.'},{title:'Restore the habitat',text:'For peat-swamp sites, restore appropriate water conditions and prevent repeat fires. Planting alone does not repair a drained peatland.'},{title:'Grow local diversity',text:'Use verified local seeds and nursery plants from multiple parent trees. Match species to habitat and monitor establishment over years.'}].map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div><Sources items={[{label:'BNF · restoration practice and monitoring',url:'https://borneonaturefoundation.org/restoration/25-years-of-restoring/'},{label:'Peat-swamp tree restoration review · 2022',url:'https://doi.org/10.1111/1365-2664.14232'}]}/><h2 className="spaced">Documented planting leads</h2><div className="leads"><article><mark>Historical lead · 2020</mark><h3>Kereng Bangkirai & Sabaru nurseries</h3><p>Central Kalimantan · BNF documented balangeran and gerunggang among locally raised plants. Current stocks and collection permissions are unverified.</p><Sources items={[{label:'Read nursery record',url:'https://borneonaturefoundation.org/uncategorized/thousands-of-seeds-to-reforest-specific-rehabilitation-areas/'}]}/></article><article><mark>Research lead · 2024</mark><h3>Banjar community cultivation</h3><p>South Kalimantan · Cultivated kasturi provides a conservation starting point. Verify plant identity, diversity and current availability before propagation.</p><Sources items={[{label:'Read conservation study',url:'https://ojs.unud.ac.id/index.php/bio/article/download/101686/55584/'}]}/></article></div><p className="note">Extinct in the wild is a conservation category: cultivated plants can survive. The historical listing is not evidence of extinction caused by this fire season.</p></section></TabsContent>
 <TabsContent value="daily"><section className="content"><label>15 DAYS · 9–23 SEPTEMBER 2026</label><h2>An evidence trail, every day.</h2><p>Target review time: 17:00 WIB / 18:00 WITA. {data.monitoring.label}.</p><div className="days">{Array.from({length:15},(_,i)=>{const d='2026-09-'+String(i+9).padStart(2,'0');return <button key={d} aria-pressed={date===d} className={date===d?'on':''} onClick={()=>setDate(d)}><small>SEP</small><b>{i+9}</b><span>{data.reports.some(r=>r.date===d)?'Reviewed':'No report'}</span></button>})}</div><article className="report"><mark>{report?'Evidence review':'No report yet'}</mark><h3>{date}</h3>{report?<><p>{report.summary}</p><h4>Plant mortality</h4><p>{report.mortality}</p><h4>Availability</h4><p>{report.availability}</p><h4>Coverage</h4><p>{report.coverage}</p><Sources items={report.sources}/></>:<p>No observations are stored for this date. This is not a zero-fire or zero-loss result.</p>}</article></section></TabsContent></Tabs>
 <footer><b><Leaf size={17}/>HutanWatch</b><p>Hotspots indicate possible fire activity. They do not identify plants, prove death or change an IUCN category. Conservation labels retain their source dates.</p><a href="https://github.com/fafarras22/kalimantan-flora-watch" target="_blank" rel="noreferrer">Project & sources</a></footer></main>
}
